"""empty message

Revision ID: 060644ff4b65
Revises: 10719c302e95
Create Date: 2026-01-04 21:57:46.060662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '060644ff4b65'
down_revision: Union[str, Sequence[str], None] = '10719c302e95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_datas', sa.Column('hight', sa.Integer(), nullable=False))
    op.add_column('user_datas', sa.Column('weight', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_datas', 'weight')
    op.drop_column('user_datas', 'hight')
    # ### end Alembic commands ###
