"""empty message

Revision ID: 10719c302e95
Revises: 88767f93f355
Create Date: 2025-12-31 18:53:22.655672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10719c302e95'
down_revision: Union[str, Sequence[str], None] = '88767f93f355'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TABLE user_infos
        ALTER COLUMN subscription_duration
        TYPE TIMESTAMP WITH TIME ZONE
        USING CASE 
               WHEN subscription_duration IS NULL THEN NULL
               ELSE to_timestamp(subscription_duration)
            END
""")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TABLE user_infos
        ALTER COLUMN subscription_duration
        TYPE INTEGER
        USING CASE
               WHEN subscription_duration IS NULL THEN NULL
                ELSE EXTRACT(EPOCH FROM subscription_duration)::INTEGER 
            END
""")
    # ### end Alembic commands ###