"""empty message

Revision ID: 1efb4df81e5b
Revises: 
Create Date: 2025-12-17 14:11:52.392212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1efb4df81e5b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_datas')
    op.drop_table('user_infos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_infos',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('user_infos_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('tg_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('paid_subcreption', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_infos_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('user_datas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_us_info', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('gender', postgresql.ENUM('man', 'woman', name='genderpeople'), autoincrement=False, nullable=False),
    sa.Column('activity', postgresql.ENUM('low', 'middle', 'hight', 'very_hight', name='activitypeople'), autoincrement=False, nullable=False),
    sa.Column('sleep_time', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('bad_habbits', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('additional_information', sa.VARCHAR(length=2500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_us_info'], ['user_infos.id'], name=op.f('user_datas_id_us_info_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_datas_pkey'))
    )
    # ### end Alembic commands ###
