"""empty message

Revision ID: 6188811e6e68
Revises: 88b9a42acab7
Create Date: 2026-01-16 21:59:38.051906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6188811e6e68'
down_revision: Union[str, Sequence[str], None] = '88b9a42acab7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_datas', 'hight',
               existing_type=sa.INTEGER())
    op.alter_column('user_datas', 'weight',
               existing_type=sa.INTEGER())
    op.add_column('user_infos', sa.Column('subscription_warned', sa.Boolean()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_infos', 'subscription_warned')
    op.alter_column('user_datas', 'weight',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_datas', 'hight',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
