"""empty message

Revision ID: 879b23a96f85
Revises: 47f660d55fe9
Create Date: 2025-12-27 17:33:55.446773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '879b23a96f85'
down_revision: Union[str, Sequence[str], None] = '47f660d55fe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_infos', 'subscription_duration',
               existing_type=sa.INTEGER(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_infos', 'subscription_duration',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
