"""empty message

Revision ID: 88b9a42acab7
Revises: d9e0dcd7dda8
Create Date: 2026-01-16 21:57:03.735369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88b9a42acab7'
down_revision: Union[str, Sequence[str], None] = 'd9e0dcd7dda8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_datas', 'hight',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_datas', 'weight',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('user_infos', sa.Column('subscription_warned', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_infos', 'subscription_warned')
    op.alter_column('user_datas', 'weight',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_datas', 'hight',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
