"""empty message

Revision ID: 8d32fb319903
Revises: 6188811e6e68
Create Date: 2026-02-23 20:36:55.750514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d32fb319903'
down_revision: Union[str, Sequence[str], None] = '6188811e6e68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_datas', 'hight',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_datas', 'weight',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_infos', 'tg_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('user_infos', 'subscription_warned',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_infos', 'subscription_warned',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user_infos', 'tg_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('user_datas', 'weight',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_datas', 'hight',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
