"""empty message

Revision ID: d9e0dcd7dda8
Revises: 060644ff4b65
Create Date: 2026-01-04 21:59:18.330324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9e0dcd7dda8'
down_revision: Union[str, Sequence[str], None] = '060644ff4b65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_datas', sa.Column('hight', sa.Integer(), nullable=True))
    op.add_column('user_datas', sa.Column('weight', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_datas', 'weight')
    op.drop_column('user_datas', 'hight')
    # ### end Alembic commands ###
